using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;

namespace ProyectoFinal
{
    public partial class frmAsignProducts : DevExpress.XtraEditors.XtraForm
    {
        DataAccess da = new DataAccess();
        string IDSucursal = "";
        public frmAsignProducts()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource1.Fill();
        }

        private void frmAsignProducts_Load(object sender, EventArgs e)
        {
            LoadData();
        }

        public void LoadData()
        {
            //Cargamos las Sucursales, Productos y presentaciones.
            //SUCURSALES            
            gridLookUpSucursales.Properties.DataSource = da.fillDataTable("SELECT id_sucursal, nombre_sucursal from tblSucursal");
            gridLookUpSucursales.Properties.DisplayMember = "nombre_sucursal";
            gridLookUpSucursales.Properties.ValueMember = "id_sucursal";

            //
            //PRODUCTOS
            //
            gridLookUpProduct.Properties.DataSource = da.fillDataTable("SELECT id_producto, nombre_producto from tblProducto");
            gridLookUpProduct.Properties.DisplayMember = "nombre_producto";
            gridLookUpProduct.Properties.ValueMember = "id_producto";            

        }

     

        private void btnCancel_Click(object sender, EventArgs e)
        {
            this.Close();
        }

        private void btnAceptar_Click(object sender, EventArgs e)
        {
            //AGREGANDO EL DATO A LA BASE,             
            //Validando si ya existe el producto en la sucursal.
            string query = "SELECT id_Producto from tblAsignacionProducto WHERE id_sucursal={0} AND id_producto='{1}'";
            query = string.Format(query, gridLookUpSucursales.EditValue.ToString(), gridLookUpProduct.EditValue.ToString());
            DataTable dt= da.fillDataTable(query);
            if (dt.Rows.Count <= 0)
            {
                try
                {
                    //insertamos el dato.
                    //PRIMERO EN TABLASIGNACION PRODUCTO

                    string command = "INSERT INTO tblAsignacionProducto(id_sucursal, id_producto) VALUES ({0},'{1}')";
                    command = string.Format(command, gridLookUpSucursales.EditValue.ToString(), gridLookUpProduct.EditValue.ToString());
                    da.executeCommand(command);

                    MessageBox.Show("Producto Agregado correctamente. ", "Informacion", MessageBoxButtons.OK, MessageBoxIcon.Information);
                    //Recargamos la tabla para que muestre los cambios.
                    


                }
                catch (Exception ex)
                {
                    MessageBox.Show("Error al asignar el producto. \n Detalles del error: " + ex.Message);                    
                }
                finally
                {
                    sqlDataSource1.Fill();
                }
            }
            else
            {
                MessageBox.Show("El producto que desea agregar ya existe en la Sucursal.","Informacion",MessageBoxButtons.OK,MessageBoxIcon.Information);
            }



            sqlDataSource1.Fill();
        }
    }
}